# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectModeEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
import sys

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication, QWidget


class Ui_DetectModeEditor(QWidget):
    def setupUi(self, DetectModeEditor):
        DetectModeEditor.setObjectName("DetectModeEditor")
        DetectModeEditor.resize(575, 588)


        self.verticalLayout = QtWidgets.QVBoxLayout(DetectModeEditor)
        self.verticalLayout.setObjectName("verticalLayout")
        self.funcListWidget = QtWidgets.QListWidget(DetectModeEditor)
        self.funcListWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.funcListWidget.sizePolicy().hasHeightForWidth())
        self.funcListWidget.setSizePolicy(sizePolicy)
        self.funcListWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.funcListWidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.funcListWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.funcListWidget.setObjectName("funcListWidget")
        self.verticalLayout.addWidget(self.funcListWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.stepListWidget = QtWidgets.QListWidget(DetectModeEditor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stepListWidget.sizePolicy().hasHeightForWidth())
        self.stepListWidget.setSizePolicy(sizePolicy)
        self.stepListWidget.setMaximumSize(QtCore.QSize(120, 16777215))
        self.stepListWidget.setObjectName("stepListWidget")
        self.horizontalLayout.addWidget(self.stepListWidget)
        self.stepArgWidget = QtWidgets.QStackedWidget(DetectModeEditor)
        self.stepArgWidget.setObjectName("stepArgWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.stepArgWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stepArgWidget.addWidget(self.page_2)
        self.horizontalLayout.addWidget(self.stepArgWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(DetectModeEditor)
        self.stepArgWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(DetectModeEditor)

    def retranslateUi(self, DetectModeEditor):
        _translate = QtCore.QCoreApplication.translate
        DetectModeEditor.setWindowTitle(_translate("DetectModeEditor", "模式编辑"))



if __name__ == '__main__':
    app = QApplication(sys.argv)
    dialog = Ui_DetectModeEditor()
    dialog.show()
    sys.exit(app.exec_())