# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'detectModeEdit.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QDialog

from ui.argument_widget import StackedWidget
from ui.func_list import FuncListWidget
from ui.func_steps import FuncStepsWidget


class Ui_ModeEditor(QDialog):
    currentStep = -1

    def __init__(self, parent=None):
        super().__init__(parent)
        self.mainWindow = parent
        self.setupUi()
        self.loadSteps()

    def setupUi(self):
        self.resize(804, 397)
        self.verticalLayout = QtWidgets.QVBoxLayout(self)
        self.verticalLayout.setObjectName("verticalLayout")
        # funcs list
        self.funcListWidget = FuncListWidget(self)
        self.funcListWidget.setEnabled(True)
        funcsSizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        funcsSizePolicy.setHorizontalStretch(0)
        funcsSizePolicy.setVerticalStretch(0)
        funcsSizePolicy.setHeightForWidth(self.funcListWidget.sizePolicy().hasHeightForWidth())
        self.funcListWidget.setSizePolicy(funcsSizePolicy)
        self.funcListWidget.setMaximumSize(QtCore.QSize(16777215, 50))
        self.funcListWidget.setFlow(QtWidgets.QListView.LeftToRight)
        self.funcListWidget.setLayoutMode(QtWidgets.QListView.SinglePass)
        self.funcListWidget.setObjectName("funcListWidget")
        # end func list
        self.verticalLayout.addWidget(self.funcListWidget)

        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout.setAlignment(QtCore.Qt.AlignLeft)
        # steps list
        self.stepListWidget = FuncStepsWidget(self)
        stepsSizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Expanding)
        stepsSizePolicy.setHorizontalStretch(0)
        stepsSizePolicy.setVerticalStretch(0)
        stepsSizePolicy.setHeightForWidth(self.stepListWidget.sizePolicy().hasHeightForWidth())
        self.stepListWidget.setSizePolicy(stepsSizePolicy)
        self.stepListWidget.setMaximumSize(QtCore.QSize(120, 16777215))
        self.stepListWidget.setObjectName("stepListWidget")
        self.horizontalLayout.addWidget(self.stepListWidget)

        self.stepArgWidget = StackedWidget(self)
        self.horizontalLayout.addWidget(self.stepArgWidget)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.stepArgWidget.setCurrentIndex(1)

        self.buttonsLayout = QtWidgets.QHBoxLayout(self)
        self.buttonsLayout.setObjectName("buttonsLayout")
        btn_save = QtWidgets.QToolButton(self)
        btn_save.setObjectName("btn_save")
        btn_save.setText("保存")
        btn_save.clicked.connect(self.accept)
        btn_cancel = QtWidgets.QToolButton(self)
        btn_cancel.setObjectName("btn_cancel")
        btn_cancel.setText("取消")
        btn_cancel.clicked.connect(self.reject)
        self.buttonsLayout.addWidget(btn_save)
        self.buttonsLayout.addWidget(btn_cancel)
        self.verticalLayout.addLayout(self.buttonsLayout)

    # def saveDetectFlow(self):
    #     self.accept()
    #
    #
    # def resetDetectFlow(self):
    #     self.reject()

    def loadSteps(self):
        detectFlow = self.mainWindow.getDetectFlow()
        for step in detectFlow:
            widget = step.getWidget()
            use_item = type(widget)()
            use_item.params = step.getArguments()
            self.stepListWidget.addItem(use_item)
        # stackedWidget隐藏
        self.stepArgWidget.hide()
